### ISSUE TITLE
Update for 1.0

### ISSUE THREAD

**Issue by SilverPaladin** [ladariha/PolymerForNB#2]
Polymer is 1.0 now, and the names of things has changed a lot.

**Comment by Chris2011** [comment]
I think you can change it by your own and make a pull request, I thought about it too. :)

**Comment by ladariha** [comment]
I must admit I don't have a lot of time for this now. I was looking at it a while back to create some script to generate the json file automatically but I didn't find any sources to parse except of the web pages of Polymer as such which didn't look friendly. Should there be some kind of "definition" files with some structure to recognize, it would be cool

**Comment by ladariha** [comment]
I'll try to look at it over the weekend. There is JSON with possibly all elements
https://elements.polymer-project.org/catalog.json

and then e.g. particular element
https://elements.polymer-project.org/data/docs/gold-email-input.json

Based on this it should not be hard to generate the customs.json by a script

**Comment by Chris2011** [comment]
Sounds nice, thx :)

**Comment by ladariha** [comment]
First try is finished, new customs.js file is now in https://github.com/ladariha/PolymerForNB/blob/master/dist/customs.json and there is also a way to "refresh" it should someone want. The new version contains also element and attribute descriptions.
 Disclaimer: I've checked only some basic usecases, not all elements :) 

Thanks

**Comment by Chris2011** [comment]
Thx :)
