### ISSUE TITLE
file is too big error

### ISSUE THREAD

**Issue by carljmosca** [ladariha/PolymerForNB#4]
The customs.json file is too big when NetBeans opens the project (on OS X platform).

**Comment by ladariha** [comment]
Sorry to hear that. What NetBeans version do you have? Have you used the custom.js from this repo or created a fresh new one (if so, what is the file size?)? The one in this repository works on my Linux with NetBeans 8.1. I guess I can either create light version (e.g. with stripped description up to the first dot character) of customs.json

**Comment by carljmosca** [comment]
NetBeans 8.1 (patch 1) custom.js was from the repo

**Comment by damiusen** [comment]
I found a workaround. You need to minify de json and now works.
http://www.httputility.net/json-minifier.aspx

**Comment by Chris2011** [comment]
Maybe you can try netbeans 8.2
